name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: jgierer12/npm-auth-gpr@dist
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: npm install
      - run: npm run lint
